### ISSUE TITLE
Duplicate and inconsistent variables completion 

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#93] opened 2019-06-13 15:05 UTC
Why is this plugin adding duplicate variables completion:
![image](https://user-images.githubusercontent.com/4896363/59444030-6d35de80-8dfd-11e9-8300-8f7a0e524432.png)

It is also inconsistent with standard PhpStorm completion (`$` prefix ...)

**Comment by klesun** [comment] 2019-06-13 19:27
Thanks for the report.
I guess the inconsistency is the reason of duplicates.

**Comment by klesun** [comment] 2019-06-13 19:49
Reproduces this way:
![image](https://user-images.githubusercontent.com/5202330/59462944-4df67b80-8e14-11e9-8906-defd8f7c3c5d.png)

**Comment by klesun** [comment] 2019-06-13 21:34
Fixed in [2019.06.13.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64014)

**Closed by klesun** 2019-06-13 21:34 UTC
Labels: awaits deployment, bug
