### ISSUE TITLE
Constants appear as static class variables

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#66] opened 2019-03-08 15:04 UTC
I don't understand this:

![image](https://user-images.githubusercontent.com/4896363/54036375-c7e6eb00-41bb-11e9-8ff9-fcc4e87796a5.png)

These variables do not exist. Why are they listed here?

**Comment by klesun** [comment] 2019-03-08 21:39
Oh, sorry, my bad. Apparently I mistakenly treat constants as properties.Will fix soon.

**Comment by klesun** [comment] 2019-03-08 22:19
Hm, though I could not reproduce this... Could it be the issue fixed in https://github.com/klesun/deep-assoc-completion/commit/56ab8c5fedb70b76fde43c5036982233c958883f? It was release [2019.02.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/58374), is your version of the plugin below that maybe?

**Comment by klesun** [comment] 2019-03-08 22:37
Sorry, never mind, it does reproduce on latest release after all...

**Comment by klesun** [comment] 2019-03-09 12:36
Thank you for the report. Fixed in [2019.03.09.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/59242)

**Closed by klesun** 2019-03-09 12:36 UTC
Labels: awaits deployment
