### ISSUE TITLE
initialize variable by $GLOBALS

### ISSUE THREAD

**Issue by ooghry** [klesun/deep-assoc-completion#52] opened 2018-10-29 21:42 UTC
Hi there
Assume I have a class like this.
```php
class test{
    public function myMethod($array){
        foreach($array as $key => $value){
            $GLOBALS[$key] = $value;
        }
    }
}
```
Is that your plugin's job provides variable in autocomplete or PHPStorm?
Any comment would be appreciated

**Comment by klesun** [comment] 2018-10-29 23:20
Hi. It's my plugin. PHPStorm provides to me the places in project where variable named `$GLOBALS` is referenced and then I calculate it's content with the plugin as if it was a normal variable.

**Comment by klesun** [comment] 2018-10-30 00:19
If, by chance, you were actually asking whether `$key` var is suggested by my plugin or phpstorm, then it's phpstorm. My plugin currently only suggests string literal key names, methods and properties - the stuff phpstorm does not resolve itself.

**Comment by klesun** [comment] 2018-11-06 16:18
@ooghry, did I answer your question? Do you want some improvements on how `$GLOBALS` completion gets inferred like remembering what values got assigned to it in the `foreach`?
Any comment would be appreciated =-D.

**Comment by ooghry** [comment] 2018-11-06 17:57
Thank you for your reply
Now, for some reason, I do not know the whole auto complete has been failed.Certainly your plugin is not the problem, but I can not test it.
Thank you again and if you would like, you can close this issue.

**Comment by klesun** [comment] 2018-11-06 17:58
thanks

**Comment by klesun** [comment] 2018-11-06 18:10
Um, just to be safe, are you sure my plugin is not the problem? It _does_ interrupt completion from other sources occasionally when it gets in infinite recursion when there are bugs. Do you still get no completion when you disable my plugin in _Settings -> Plugins -> deep-assoc-completion_ and restart phpstorm?

**Comment by ooghry** [comment] 2018-11-06 21:37
Currently my problem is not about GLOBALS,completion failed totally
- notice to error between `return time`
- `pubf` is available but `pubsf` does not exist
-  `forek` does not work correctly
- and some many other break


![completion](https://user-images.githubusercontent.com/200244/48095092-13e34c80-e229-11e8-8216-e1a411ca81b0.gif)

**Comment by ooghry** [comment] 2018-11-06 22:11
I disable almost all plugins(except yours) and try this code but `myVar` does not show:
```php
class get{
    public function random($array)
    {
        foreach($array as $var){
            $GLOBALS[$var] = rand(1,100);
        }
    }
}
$get = new get;
$get->random(array('myVar'));
echo $myVar;
```
meantime I don't have that problem you stated.

**Comment by klesun** [comment] 2018-11-11 13:09
Wow, something is really broken in your phpstorm. `forek` and class name completion problems are very unlikely to be caused by my plugin as you said. And other problems do not hapen in my installation as well:
![bandicam20181111140918461](https://user-images.githubusercontent.com/5202330/48312765-5e175580-e5bc-11e8-8aa5-d3aacafe1e1e.gif)
So I'm afraid I can't help you here in any way except suggesting to re-install phpstorm or asking JetBrains support for help: https://youtrack.jetbrains.com/issues/WI

It's probably a small consolation, but I fixed the issue caused by my plugin I described in https://github.com/klesun/deep-assoc-completion/issues/52#issuecomment-436357713 (the one you could not reproduce =3) https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/51949

About your last comment:
```php
$get = new get;
$get->random(array('myVar'));
echo $myVar;
```
There is currently no such feature as variable name completion inferred from `$GLOBALS[]` assignment. I could add it if you wish, but I guess it's just a misunderstanding, so I guess I'll close this issue.

**Comment by ooghry** [comment] 2018-11-11 23:11
>  I could add it if you wish

Yes, it would be nice if it is possible to completion work on this code:
```php
$get = new get;
$get->random(array('myVar'));
echo $myVar;
```
should I open new issue or ...?

**Comment by klesun** [comment] 2018-11-12 00:40
I'll implement this in context of this issue.

**Comment by klesun** [comment] 2018-11-12 02:04
Added very basic completion for a start.
![image](https://user-images.githubusercontent.com/5202330/48322378-f13da300-e62f-11e8-95ec-0efdf8aad055.png)
Currently infers only keys declared in the script top-level scope. Supporting `$GLOBALS` var declaration in a function will require some time.

**Comment by klesun** [comment] 2018-11-13 00:38
ting `$GLOBALS` var declaration in a function:
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/51988

![image](https://user-images.githubusercontent.com/5202330/48383123-29ef8200-e6ed-11e8-97cc-aa04cc6803ef.png)

**Closed by klesun** 2018-11-13 00:38 UTC
Labels: in progress

**Comment by klesun** [comment] 2018-11-13 12:04
You may want to hit _Ctrl + Space_ if options don't show on their own (there is a resolution depth limit for implicit auto-complete popup).
