### ISSUE TITLE
Worker exited due to exception NoClassDefFoundError

### ISSUE THREAD

**Issue by EvgeniiR** [klesun/deep-assoc-completion#81] opened 2019-05-15 09:36 UTC
IDE catches Exception, stacktrace.txt:

<pre>Worker exited due to exception

java.lang.NoClassDefFoundError: com/jetbrains/php/lang/psi/stubs/indexes/expectedArguments/PhpExpectedFunctionArgumentsIndex
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findFqnMetaArgType(UsageResolver.java:264)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.findMetaArgType(UsageResolver.java:273)
	at org.klesun.deep_assoc_completion.resolvers.UsageResolver.lambda$null$85(UsageResolver.java:279)
	at org.klesun.lang.IIt.lambda$fap$5(IIt.java:53)
	at org.klesun.lang.iterators.FlatMapIterator.lambda$new$1(FlatMapIterator.java:18)
	at org.klesun.lang.iterators.MapIterator.next(MapIterator.java:23)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:26)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:37)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:39)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.MemIt$1.hasNext(MemIt.java:38)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:34)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:39)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.iterators.FlatMapIterator.getNextSup(FlatMapIterator.java:39)
	at org.klesun.lang.iterators.FlatMapIterator.hasNext(FlatMapIterator.java:48)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at org.klesun.lang.iterators.MapIterator.hasNext(MapIterator.java:19)
	at org.klesun.lang.iterators.EndIterator.getCurrent(EndIterator.java:20)
	at org.klesun.lang.iterators.EndIterator.hasNext(EndIterator.java:41)
	at org.klesun.lang.iterators.FilterIterator.getCurrent(FilterIterator.java:25)
	at org.klesun.lang.iterators.FilterIterator.hasNext(FilterIterator.java:38)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.klesun.lang.It.arr(It.java:113)
	at org.klesun.deep_assoc_completion.go_to_decl_providers.MainGoToDecl.getGotoDeclarationTargets(MainGoToDecl.java:98)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:279)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:474)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:453)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1700(CtrlMouseHandler.java:89)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:720)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2200(CtrlMouseHandler.java:651)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:697)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.php.lang.psi.stubs.indexes.expectedArguments.PhpExpectedFunctionArgumentsIndex PluginClassLoader[lv.midiana.misc.phpstorm-plugins.deep-keys, 2019.05.08.001] com.intellij.ide.plugins.cl.PluginClassLoader@2dd4c299
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 62 more</pre>

At the time of the exception did not have any action, just opened class which wrote yesterday

**Comment by klesun** [comment] 2019-05-15 10:28
@EvgeniiR, what verison of plugin are you using? And what is the version of your IDE?

**Comment by klesun** [comment] 2019-05-15 10:30
I screwed up back in the 2019.04.24.001 release, this could possibly be it...

**Comment by EvgeniiR** [comment] 2019-05-16 17:06
IDE info:
PhpStorm 2018.3.4
Build #PS-183.5429.47, built on February 8, 2019
JRE: 1.8.0_202-b26 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.14.101-1-MANJARO


Plugin version v2019.05.08.001

**Comment by klesun** [comment] 2019-05-16 17:08
thanks!

**Comment by klesun** [comment] 2019-05-16 19:09
Reproduced.
![image](https://user-images.githubusercontent.com/5202330/57880184-a6cef600-780d-11e9-88d4-03135e927613.png)
Sorry, looks like I used wrong min phpstorm version in plugin dependencies. Will add a try-catch in the next release for pre-2019 installations.

**Comment by klesun** [comment] 2019-05-16 21:05
Fixed in [2019.05.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/62419)

**Closed by klesun** 2019-05-16 21:05 UTC
Labels: bug
