### ISSUE TITLE
class inherit question

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#73] opened 2019-04-21 05:29 UTC
great plugin!

```php
<?php

class Base
{

    /**
     * @return array
     */
    public static function sample()
    {
        return ['stub_id' => 1];
    }

    /**
     * @param array $filters
     * @param array $fields =static::sample()
     *
     * @return array
     */
    public static function find($filters, $fields = null)
    {
        return [];
    }
}

class Child extends Base
{
    public static function sample()
    {
        return ['user_id' => 1, 'user_name' => 'mark'];
    }
}

Child::find([], ['!!caret!!']);
```
!!caret!! complete only `stub_id` not `user_id` and `user_name`.

**Comment by manaphp** [comment] 2019-04-22 08:43
`static` support is very important, when use `model`!!!

**Comment by klesun** [comment] 2019-04-22 11:52
I'll take a look if this can be done without much blood... Resolving static would probabl cmplicate things a lot both code-wise and performance-wise.

**Comment by manaphp** [comment] 2019-04-22 11:55
`model` needs many fields name auto completion!!

**Comment by klesun** [comment] 2019-04-27 17:18
Related issue: #42

**Comment by klesun** [comment] 2019-04-27 20:05
Added `static::` support in doc comments in [2019.04.27.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61505)
![image](https://user-images.githubusercontent.com/5202330/56854533-e60dd380-6940-11e9-95bf-f93dd693adb6.png)

**Comment by manaphp** [comment] 2019-04-28 14:07
thanks,very good!!

**Comment by manaphp** [comment] 2019-04-29 07:03
> 
> 
> Added `static::` support in doc comments in [2019.04.27.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61505)
> ![image](https://user-images.githubusercontent.com/5202330/56854533-e60dd380-6940-11e9-95bf-f93dd693adb6.png)

if `find` is not `static` method ,it does not work..

**Comment by klesun** [comment] 2019-04-29 08:47
How does your phpdoc looks like when it's not static?

**Comment by klesun** [comment] 2019-04-29 08:51
Oh, reproduced. I'll take a look.

**Comment by manaphp** [comment] 2019-04-29 08:52
> 
> 
> How does your phpdoc look like when it's not static?
```php
  /**
     * @param string $field =array_keys(static::sample())[$i]
     *
     * @return bool
     */
    public function hasField($field)




$city =City::first([]);
$city->hasField('!caret!')

```

**Comment by klesun** [comment] 2019-04-29 09:05
There is a temprary hackish workaround: if you specify it like this:
```
* @param string $field =array_keys($this->sample())[$i]
```
It will work in a non-static method

**Comment by klesun** [comment] 2019-04-29 09:07
But I guess I'll make it possibly to use `static::` as well...

**Comment by manaphp** [comment] 2019-04-29 09:18
> 
> 
> But I guess I'll make it possibly to use `static::` as well...

consistency is very import..

**Comment by klesun** [comment] 2019-04-29 09:30
Fixed in beta release: [2019.04.29.001](https://plugins.jetbrains.com/files/9927/61570/deep-assoc-completion.jar?updateId=61570&pluginId=9927&family=intellij)

Will be in stable repo within a week.

**Comment by klesun** [comment] 2019-05-05 11:15
Just uploaded to the main repo - https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61899
You should now see 2019.04.29.001 in the list in your IDE updates

**Closed by klesun** 2019-05-05 11:15 UTC
Labels: awaits deployment
