### ISSUE TITLE
d-a-c makes PhpStorm's check for missing methods in array callables fail

### ISSUE THREAD

**Issue by jhard** [klesun/deep-assoc-completion#138] opened 2020-01-16 17:28 UTC
Given
```
    class A {}
    call_user_func([(new A()), "doesNotExist"]);
```
PHPStorm would warn about "doesNotExist" not existing in class A. When deep-assoc-completion is active, it not longer warns.

PhpStorm 2019.3.1
Build #PS-193.5662.63, built on December 19, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-72-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8

**Comment by klesun** [comment] 2020-01-16 17:52
Hm, thanks, I'm taking a look.
Could you, please, lookup, what is the name of this inspection by placing caret n highlighted text and pressing _alt + enter_
(it seems to be disabled in my settings, as I don't see the highlight even without the plugin).

![image](https://user-images.githubusercontent.com/5202330/72549598-ad7ca400-3899-11ea-9f92-f23f7cd98ff4.png)

**Comment by klesun** [comment] 2020-01-16 17:54
Is it "Undefined method"?
![image](https://user-images.githubusercontent.com/5202330/72549751-f3396c80-3899-11ea-8826-cb9a3d4c48af.png)

**Comment by klesun** [comment] 2020-01-16 17:55
Btw, do you have this "Notify on accessing member of mixed, object, stdClass" enabled? Could it possibly be that you changed it in same session as the removal of the plugin before restart?

**Comment by klesun** [comment] 2020-01-16 18:02
Could you, plese, post a complete minimal example of the file?

**Comment by jhard** [comment] 2020-01-16 18:04
It's "undefined callback". I mistook it to report things accessed from within callbacks, but it does this.
I had previously thought this to be an issue in PhpStorm (https://youtrack.jetbrains.com/issue/WI-50785), and have enabled and disabled d-a-c with Restarts in between (and without changing anything else) multiple times to make absolutely sure that it's the cause. I had started with an empty project and enabled all PHP inspections.
![d-a-c-undefined-callback](https://user-images.githubusercontent.com/1022803/72550402-f8df8400-3892-11ea-8c93-d9ad265b43b6.png)


Re: "Notify on accessing member of mixed, object, stdClass", I can't find it by searching in the settings, what key would it be under?

**Comment by jhard** [comment] 2020-01-16 18:08
```
<?php

class A {}
call_user_func([(new A()), "doesNotExist"]);
```

Is really all there is ;)

**Comment by klesun** [comment] 2020-01-16 18:11
Yeah, thanks, reproduced, will deal with it. "Undefined callback" inspection was disabled in my settings.

Most likely caused by https://github.com/klesun/deep-assoc-completion/issues/115

**Comment by klesun** [comment] 2020-01-16 21:23
Fix released in [2020.01.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/75960)
![image](https://user-images.githubusercontent.com/5202330/72563678-dd867000-38b6-11ea-8d9a-c5bfb81a1398.png)

**Closed by klesun** 2020-01-16 21:23 UTC
Labels: status: todo, type: bug

**Comment by Falseclock** [comment] 2020-02-04 05:56
@klesun 
that's bad fix for me cause used "self" notation to remove warns that protected methods are not used 

```php
	protected $methodMap     = [
		self::ACTION_DEFAULT           => [ "self", "mainPage" ],
		self::ACTION_FINGERPRINT       => [ "self", "fingerPrint" ],
		self::ACTION_CONTACTS          => [ "self", "contactPage" ],
		self::ACTION_TENDER_LOT_WIDGET => [ "self", "tenderLotWidget" ],
	];
	/**
	 * Страница с контактной информацией
	 *
	 * @return $this
	 */
	protected function contactPage() {
		$this->skinVars->title = "Контактная информация";
		$this->skinVars->noJs = true;
		$this->skinVars->jsNameOverride = "Contacts";

		return $this;
	}

	/**
	 * Метод вызывается с любой страницы, если нету фингерпринта
	 *
	 * @return $this
	 * @throws Exception
	 */
	protected function fingerPrint() {
		$this->setSkin(SkinText::create());

		$this->vars->text = 1;

		$this->site->Session->setFingerPrint($this->site->getInputVarStr(self::PARAM_FINGERPRINT, 32));

		return $this;
	}
```

**Comment by klesun** [comment] 2020-02-04 08:11
@Falseclock, note that in your example you are referencing non-static method `contactPage()` statically via `"self"`. If you use:
```php
protected $methodMap     = [
    self::ACTION_DEFAULT           => [ $this, "mainPage" ],
    self::ACTION_FINGERPRINT       => [ $this, "fingerPrint" ],
    self::ACTION_CONTACTS          => [ $this, "contactPage" ],
    self::ACTION_TENDER_LOT_WIDGET => [ $this, "tenderLotWidget" ],
];
```
It will be much easier for the plugin to understand your code.

**Comment by klesun** [comment] 2020-02-04 08:21
@Falseclock, sorry about that, filed a separate issue https://github.com/klesun/deep-assoc-completion/issues/146.

Would you mind using `self::class` instead of `'self'`? Attempts to resolve any _pair of strings_ as an array as a method may cause performance issues...
